'use strict';
const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const moods=[{name:'开心',emoji:'😊',color:'#ffe2ad',score:5},{name:'平静',emoji:'😌',color:'#c9ebe2',score:4},{name:'低落',emoji:'😔',color:'#d9d6ff',score:2},{name:'焦虑',emoji:'😟',color:'#ffccc0',score:2},{name:'生气',emoji:'😠',color:'#ffc7c7',score:1},{name:'压力大',emoji:'😣',color:'#ffdeb5',score:2}];
const triggers=['工作','学习','感情','家庭','社交','健康','金钱','睡眠'],KEY='xinqing-v2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={entries:[],stories:[],reactions:{},feedback:[]};
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&typeof saved==='object'){state.entries=Array.isArray(saved.entries)?saved.entries.filter(e=>e&&moods.some(m=>m.name===e.mood)&&Number.isFinite(e.time)&&e.intensity>=1&&e.intensity<=5&&Array.isArray(e.triggers)):[];state.stories=Array.isArray(saved.stories)?saved.stories.filter(s=>s&&typeof s.title==='string'&&typeof s.body==='string'&&Array.isArray(s.tags)):[];state.reactions=saved.reactions&&typeof saved.reactions==='object'?saved.reactions:{};state.feedback=Array.isArray(saved.feedback)?saved.feedback:[];}}catch{setTimeout(()=>toast('未能读取本地记录，本次可继续使用。'),100);}
let selectedMood='平静',selectedTriggers=new Set(),period=7,storyTab='all',tag='',search='',timer=null,audioContext=null,practiceStarted=0,toastTimer;
const seedStories=[
{id:'sample-1',name:'晚安小树',avatar:'🌷',time:'示例故事',title:'秋招投了 80 份简历，我开始怀疑自己是不是不适合这条路……',body:'明明已经很努力了，但还是一次次被拒。\n有时候会忍不住想，是不是我真的不够好？\n\n后来我试着把「今天做成的一件小事」写下来。哪怕只是认真吃了一顿饭，也算是在照顾自己。',tags:['秋招焦虑','职场压力'],type:'all'},
{id:'sample-2',name:'路过的云',avatar:'☁️',time:'示例故事',title:'工作第三个月，我每天都害怕领导找我。',body:'总觉得自己做得不够好，一收到消息就紧张。\n\n现在我会在下班后走一小段路，把工作留在办公室。还没有完全不焦虑，但我开始给自己一点空间。',tags:['职场压力','自我怀疑'],type:'through'},
{id:'sample-3',name:'慢慢生长',avatar:'🌱',time:'示例故事',title:'允许自己休息以后，论文终于又写了一页。',body:'卡住的时候，我总想逼自己再努力一点。\n朋友提醒我：休息也是前进的一部分。今天散步回来，我终于重新打开了文档。',tags:['论文压力','自我关怀'],type:'through'}];
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{toast('保存失败：浏览器存储不可用或空间不足。');return false;}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function face(name){const m=moods.find(m=>m.name===name)||moods[1];return '<span class="face" style="--face:'+m.color+'">'+m.emoji+'</span>';}
function moodButtons(){return '<div class="moods" role="group" aria-label="选择情绪">'+moods.map(m=>'<button type="button" class="mood '+(m.name===selectedMood?'selected':'')+'" data-mood="'+m.name+'" aria-pressed="'+(m.name===selectedMood)+'">'+face(m.name)+'<span>'+m.name+'</span></button>').join('')+'</div>';}
function pageTop(title,subtitle,action=''){return '<header class="page-top"><div><div class="eyebrow">XINQING · YOUR DAILY COMPANION</div><h1>'+title+'</h1><p>'+subtitle+'</p></div>'+(action||'<span class="top-badge">✧ 每一种情绪，都值得被看见</span>')+'</header>';}
function entriesHTML(entries,history=false){return entries.length?entries.map(e=>'<div class="entry"><time>'+(history?new Date(e.time).toLocaleDateString('zh-CN')+'<br>':'')+new Date(e.time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})+'</time>'+face(e.mood)+'<div class="entry-copy"><b>'+esc(e.mood)+' <small>· '+e.intensity+'/5</small></b><p>'+esc(e.note||'给此刻的自己，留下一点空间。')+'</p></div><span class="pill">'+esc(e.triggers[0]||'日常')+'</span></div>').join(''):'<div class="empty">今天还没有记录。<br>从一个小小的感受开始吧。</div>';}
function careRows(){return [{icon:'🍃',title:'3 分钟呼吸练习',desc:'放慢呼吸，让身体平静下来',id:'breath'},{icon:'🎵',title:'舒缓音景',desc:'听一会儿柔和的声音',id:'music'},{icon:'📝',title:'写下最担心的三件事',desc:'把焦虑从脑海中拿出来',id:'write'}].map(c=>'<button class="care-row" data-practice="'+c.id+'"><span class="care-icon">'+c.icon+'</span><div><b>'+c.title+'</b><p>'+c.desc+'</p></div><span class="arrow">›</span></button>').join('');}
function today(){const es=state.entries.filter(e=>new Date(e.time).toDateString()===new Date().toDateString());return pageTop('今天，也好好照顾自己',new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'}))+'<section class="hero"><div><div class="eyebrow">A MOMENT JUST FOR YOU</div><h1>'+(new Date().getHours()<12?'早上好':new Date().getHours()<18?'下午好':'晚上好')+'，亲爱的你</h1><p>辛苦了，今天也记得给自己一点温柔。</p><div class="quote">“ 不必时刻积极，你可以只是你自己。 ”</div></div><div class="hero-art" aria-hidden="true"><span class="moon">🌙</span><span class="plant">🪴</span><span class="cup">☕</span></div></section><div class="grid"><div class="stack"><section class="card"><div class="card-header"><h2>现在感觉怎么样？</h2><span class="text-link">此刻的你</span></div><p class="sub">没有对错，每一种感受都有它的位置。</p>'+moodButtons()+'<a href="#record" class="primary full">记录此刻心情 <span>→</span></a></section><section class="card"><div class="card-header"><h2>今日记录 <small>'+es.length+' 次</small></h2><a class="text-link" href="#history">查看全部 ›</a></div>'+entriesHTML(es)+'</section></div><div class="stack"><section class="card"><div class="card-header"><h2>给自己一点温柔</h2><a href="#care" class="text-link">更多关怀 ›</a></div>'+careRows()+'</section><a href="#insights" class="note"><span>🌱</span><div><b>听听情绪想告诉你什么</b><p>'+(state.entries.length?'已经记录了 '+state.entries.length+' 个情绪瞬间，去看看它们的规律。':'每一次记录，都是更了解自己的开始。')+'</p></div><span class="arrow">›</span></a><div class="mini-quote">你不用独自面对所有的阴天。<br><small>心晴，陪你慢慢来。</small></div></div></div>';}
function record(){return pageTop('记录情绪','停下来，听听内心的声音。')+'<form id="record-form" class="card form-wrap"><div class="steps"><span></span><span></span><span></span></div><fieldset><legend>1. 你现在的情绪是？</legend>'+moodButtons()+'</fieldset><fieldset><div class="range-head"><label for="intensity"><b>2. 情绪强度有多强？</b></label><output id="intensity-value">3/5</output></div><input id="intensity" type="range" min="1" max="5" value="3"><div class="range-labels"><span>1 · 很轻微</span><span>3</span><span>5 · 很强烈</span></div></fieldset><fieldset><legend>3. 这可能是因为什么？ <small>可多选</small></legend><div class="chips">'+triggers.map(t=>'<button type="button" class="chip '+(selectedTriggers.has(t)?'active':'')+'" data-trigger="'+t+'" aria-pressed="'+selectedTriggers.has(t)+'">'+t+'</button>').join('')+'</div></fieldset><label class="label" for="note">4. 发生了什么？ <small>可选</small></label><textarea class="field" id="note" maxlength="500" placeholder="发生了什么？此刻最想对自己说什么？"></textarea><div class="counter" id="note-count">0/500</div><p class="sub">🔒 这段心事只会保存在你的浏览器里。</p><button class="primary full" type="submit">完成记录</button></form>';}
function filteredEntries(){const since=new Date();since.setHours(0,0,0,0);since.setDate(since.getDate()-(period-1));return state.entries.filter(e=>period===0||e.time>=since.getTime());}
function insights(){
const es=filteredEntries(),counts={},mc={};es.forEach(e=>{e.triggers.forEach(t=>counts[t]=(counts[t]||0)+1);mc[e.mood]=(mc[e.mood]||0)+1;});
const ranked=Object.entries(counts).sort((a,b)=>b[1]-a[1]),top=Object.entries(mc).sort((a,b)=>b[1]-a[1])[0]?.[0];
const days=period||Math.max(7,Math.ceil((Date.now()-(es.at(-1)?.time||Date.now()))/86400000)+1);
const pts=Array.from({length:7},(_,i)=>{const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-(days-1)+Math.floor(i*days/7));const end=new Date();end.setHours(0,0,0,0);end.setDate(end.getDate()-(days-1)+Math.floor((i+1)*days/7));const group=es.filter(e=>e.time>=+start&&e.time<+end);return {label:(start.getMonth()+1)+'/'+start.getDate(),x:40+i*70,y:group.length?155-(group.reduce((s,e)=>s+moods.find(m=>m.name===e.mood).score,0)/group.length-1)*30:null};});
return pageTop('情绪里的小小发现','看见变化，也看见一直在努力的自己。','<div class="tabs">'+[[7,'近 7 天'],[30,'近 30 天'],[0,'全部']].map(([n,t])=>'<button data-period="'+n+'" class="'+(period===n?'active':'')+'">'+t+'</button>').join('')+'</div>')+'<div class="stats"><div class="stat"><span>记录次数</span><strong>'+es.length+'<small> 次</small></strong></div><div class="stat"><span>高频情绪</span><strong>'+(top||'暂无')+'</strong></div><div class="stat"><span>主要触发因素</span><strong>'+esc(ranked[0]?.[0]||'暂无')+'</strong></div></div><div class="grid"><section class="card"><div class="card-header"><h2>情绪趋势</h2><small>'+(es.length?'来自你的真实记录':'等待你的第一条记录')+'</small></div><svg class="chart" viewBox="0 0 500 195" role="img" aria-label="情绪平均趋势，空缺表示未记录"><g>'+[35,65,95,125,155].map((y,i)=>'<line x1="35" y1="'+y+'" x2="470" y2="'+y+'"/><text x="4" y="'+(y+4)+'">'+['愉悦','平静','一般','低落','不适'][i]+'</text>').join('')+'</g>'+pts.map((p,i)=>p.y!==null?((i&&pts[i-1].y!==null)?'<line x1="'+pts[i-1].x+'" y1="'+pts[i-1].y+'" x2="'+p.x+'" y2="'+p.y+'" style="stroke:#669eba;stroke-width:2"/>':'')+'<circle cx="'+p.x+'" cy="'+p.y+'" r="4" fill="#669eba"/>':'').join('')+pts.map(p=>'<text x="'+p.x+'" y="185" text-anchor="middle">'+p.label+'</text>').join('')+'</svg><p class="sub">按情绪类别粗略汇总，仅用于个人回顾，不代表心理健康评分。'+(period!==7?'每个点汇总该时间段内的记录。':'')+'</p><div class="callout">'+(es.length?'你已经为自己留下 '+es.length+' 次倾听。'+(ranked.length?'「'+esc(ranked[0][0])+'」是较常出现的关联因素，可以试着给这部分生活多一点关注。':'继续标记触发因素，帮助自己发现规律。'):'每一种感受都值得记录。积累一些日记后，这里会显示你的情绪变化。')+'</div></section><section class="card"><h2>情绪触发因素</h2><p class="sub">多选因素按总提及次数计算占比</p>'+(ranked.length?ranked.map(([t,n])=>{const p=Math.round(n/ranked.reduce((s,x)=>s+x[1],0)*100);return '<div class="trigger"><label>'+esc(t)+'</label><div class="bar"><i style="width:'+p+'%"></i></div><b>'+p+'%</b></div>';}).join(''):'<div class="empty">还没有标记触发因素</div>')+'<a class="text-link" href="#record">再记录一个情绪瞬间 →</a></section></div>';
}
function care(){return pageTop('现在适合这样做','不用急着好起来，先给自己一点支持。')+'<div class="note" style="margin-bottom:24px"><span>'+moods.find(m=>m.name===(state.entries[0]?.mood||selectedMood)).emoji+'</span><div><b>'+esc(state.entries[0]?.mood||selectedMood)+' · '+(state.entries[0]?.intensity||3)+'/5</b><p>有情绪是正常的，你并不孤单。选一个此刻愿意做的小练习。</p></div></div><div class="care-grid">'+[{id:'breath',icon:'🍃',title:'3 分钟呼吸练习',desc:'跟着圆圈的节奏，慢慢吸气、呼气。',meta:'3 MIN · 放松身体'},{id:'meditate',icon:'🧘🏻‍♀️',title:'5 分钟松弛冥想',desc:'把注意力带回身体，给大脑一个温柔的暂停。',meta:'5 MIN · 回到当下'},{id:'music',icon:'🎵',title:'舒缓音景',desc:'柔和的合成音，让思绪暂时歇一歇。',meta:'随时暂停 · 安放心绪'},{id:'write',icon:'📝',title:'写下最担心的三件事',desc:'不急着解决，先把担忧从脑海里放下来。',meta:'写作练习 · 轻一点'}].map(c=>'<button class="care-tile" data-practice="'+c.id+'"><span>'+c.icon+'</span><h2>'+c.title+'</h2><p>'+c.desc+'</p><small>'+c.meta+'　→</small></button>').join('')+'</div><div class="mini-quote">“你无法控制一切，但你可以照顾好此刻的自己。”</div><section class="card" style="text-align:center"><h2>现在感觉怎么样？</h2><div class="feedback">'+['😌 好很多','🙂 好一点','😐 没变化','😟 更糟了'].map(f=>'<button data-feedback="'+f+'">'+f+'</button>').join('')+'</div></section>';}
function storyCards(){const list=[...state.stories,...seedStories].filter(s=>(storyTab==='all'||s.type==='through')&&(!tag||s.tags.includes(tag))&&(!search||(s.title+s.body+s.tags.join('')).toLowerCase().includes(search.toLowerCase())));return list.length?list.map(s=>'<article class="card story"><div class="story-head"><span class="avatar">'+esc(s.avatar||'🌱')+'</span><div><b>'+esc(s.name)+'</b><small>'+esc(s.time||'本地分享 · 刚刚')+'</small></div></div><h2>'+esc(s.title)+'</h2><p>'+esc(s.body)+'</p><div class="chips">'+s.tags.map(t=>'<button class="chip" data-tag="'+esc(t)+'">#'+esc(t)+'</button>').join('')+'</div><div class="reactions">'+['♡ 我也经历过','◌ 抱抱你','☀ 谢谢分享'].map((r,i)=>'<button data-reaction="'+esc(s.id)+':'+i+'" aria-pressed="'+!!state.reactions[s.id+':'+i]+'" class="'+(state.reactions[s.id+':'+i]?'active':'')+'">'+r+(state.reactions[s.id+':'+i]?' · 已送出':'')+'</button>').join('')+'</div></article>').join(''):'<div class="card empty">还没有找到相关故事，换一个关键词试试。</div>';}
function stories(){return pageTop('在这里，遇见共鸣','你并不孤单，我们在这里相遇。','<a href="#share" class="primary purple">＋ 写下我的故事</a>')+'<div class="grid"><div><div class="section-actions" style="margin-bottom:18px"><div class="tabs"><button data-story-tab="all" class="'+(storyTab==='all'?'active':'')+'">我正在经历</button><button data-story-tab="through" class="'+(storyTab==='through'?'active':'')+'">我是这样走过来的</button></div></div><div class="search"><input class="field" id="story-search" type="search" placeholder="搜索你关心的话题…" aria-label="搜索故事" value="'+esc(search)+'"></div><div class="chips" style="margin-bottom:18px">'+['','秋招焦虑','职场压力','论文压力','自我怀疑'].map(t=>'<button class="chip '+(tag===t?'active':'')+'" data-tag="'+t+'">'+(t?'#'+t:'全部')+'</button>').join('')+'</div><div class="story-list" id="story-list">'+storyCards()+'</div></div><div class="stack"><div class="share-banner"><span>🪴</span><br>把心里的话说出来，<br>也是一种勇敢。</div><div class="card"><h2>一个温柔的小约定</h2><p class="sub" style="margin-top:15px">倾听，不评判。分享经历，不替别人做决定。</p><p class="sub">当前是本地演示社区。示例故事为虚构内容，你写的故事仅保存在本设备，不会发布给其他人。</p><a class="text-link" href="#share">记录自己的故事 →</a></div></div></div>';}
function share(){return pageTop('分享这个故事','你的经历，也值得被温柔地接住。')+'<form id="share-form" class="card form-wrap"><a class="back" href="#stories">‹ 返回共鸣故事</a><div class="share-banner">🪴　把心里的话说出来<br>也是一种勇敢。</div><label class="label" for="story-title">为故事写一个标题</label><input class="field" id="story-title" required maxlength="60" placeholder="从最近一个想被听见的瞬间开始"><label class="label" for="story-body">你的故事</label><textarea class="field" id="story-body" required maxlength="500" rows="7" placeholder="可以是让你困扰的经历、你的感受，或者你是如何慢慢走出来的…"></textarea><div class="counter" id="story-count">0/500</div><label class="label" for="story-topic">故事话题</label><select class="field" id="story-topic">'+['秋招焦虑','职场压力','论文压力','自我怀疑','自我关怀'].map(t=>'<option>'+t+'</option>').join('')+'</select><label class="toggle-line"><input type="checkbox" id="through">我想分享自己是怎样走过来的</label><label class="toggle-line"><input type="checkbox" id="anonymous" checked>使用匿名昵称</label><p class="sub">本地演示：内容仅保存在这台设备，不会上传或公开发布。</p><button class="primary purple full">保存故事到本地社区</button></form>';}
function profile(){return pageTop('给自己的小天地','你的记录，由你保管。')+'<section class="card form-wrap"><h2>数据与隐私</h2><p class="sub" style="margin-top:15px">目前已保存 '+state.entries.length+' 条情绪记录、'+state.stories.length+' 个故事。所有内容存储在当前浏览器，没有账号同步。清除浏览器数据会删除记录，建议定期导出备份。</p><div class="data-actions"><button class="primary blue" id="export">导出我的数据</button><button class="danger" id="clear">清除本地数据</button></div></section>';}
const routes={today,record,insights,care,stories,share,profile,history:()=>pageTop('那些被记下的瞬间','每一次倾听自己，都有意义。')+'<section class="card form-wrap">'+(state.entries.length?entriesHTML(state.entries,true):'<div class="empty">还没有记录，<a href="#record" class="text-link">写下第一条吧 →</a></div>')+'</section>'};
function render(){stopPractice();const route=location.hash.slice(1)||'today';$('#app').innerHTML=(routes[route]||today)()+'<footer class="footnote">心晴 · 记录情绪，理解自己，温柔成长<br>自我关怀工具，不提供诊断或治疗。<br><a href="#profile">我的数据与隐私</a></footer>';$$('nav a').forEach(a=>{const active=a.hash==='#'+route;a.classList.toggle('active',active);active?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current');});window.scrollTo(0,0);}
function stopPractice(){clearInterval(timer);timer=null;if(audioContext){audioContext.close().catch(()=>{});audioContext=null;}if($('#practice').open)$('#practice').close();}
function openPractice(type){
stopPractice();const d=$('#practice');practiceStarted=Date.now();
if(type==='write')$('#practice-content').innerHTML='<h2>先把担忧放下来</h2><p>写下三件担心的事，再选一件此刻能做的小事。</p><textarea id="worries" aria-label="我的担忧" class="field" maxlength="500" placeholder="1. 我担心…&#10;2. 我担心…&#10;3. 我担心…&#10;&#10;此刻，我能做的一件小事是…"></textarea><button id="save-worries" class="primary full" style="margin-top:20px">存入情绪日记</button>';
else if(type==='music')$('#practice-content').innerHTML='<span style="font-size:55px">🎵</span><h2>让心绪慢下来</h2><p>柔和音景 · 建议调低设备音量</p><button class="primary blue" id="play-sound">播放音景</button>';
else {const duration=type==='breath'?180:300;$('#practice-content').innerHTML='<h2>'+(type==='breath'?'3 分钟呼吸练习':'5 分钟松弛冥想')+'</h2><div class="breathing" id="breath-label">慢慢吸气</div><div class="timer" id="timer"></div><p id="guidance"></p><button class="primary blue" id="end-practice">结束练习</button>';const tick=()=>{const elapsed=Math.floor((Date.now()-practiceStarted)/1000),left=Math.max(0,duration-elapsed);$('#timer').textContent=Math.floor(left/60)+':'+String(left%60).padStart(2,'0');$('#breath-label').textContent=elapsed%10<4?'慢慢吸气':'轻轻呼气';$('#guidance').textContent=type==='breath'?'自然地吸气 4 秒，呼气 6 秒，不用勉强。':['找一个舒服的姿势，让肩膀放松，感受身体与椅子的接触。','觉察呼吸，不用改变它。思绪飘走时，温柔地带回来。','留意身体的感受，松开紧绷的下颌和双手。','允许念头经过，不必追着它走。','慢慢感受周围的声音，准备好时，睁开眼睛。'][Math.min(4,Math.floor(elapsed/60))];if(!left){clearInterval(timer);$('#breath-label').textContent='练习完成';$('#guidance').textContent='谢谢你，留了这段时间给自己。';$('.breathing').style.animation='none';}};tick();timer=setInterval(tick,250);}d.showModal();
}
document.addEventListener('click',async e=>{
const b=e.target.closest('button');if(!b)return;
if(b.dataset.mood){selectedMood=b.dataset.mood;$$('[data-mood]').forEach(el=>{el.classList.toggle('selected',el.dataset.mood===selectedMood);el.setAttribute('aria-pressed',el.dataset.mood===selectedMood);});}
if(b.dataset.trigger){const t=b.dataset.trigger;selectedTriggers.has(t)?selectedTriggers.delete(t):selectedTriggers.add(t);b.classList.toggle('active',selectedTriggers.has(t));b.setAttribute('aria-pressed',selectedTriggers.has(t));}
if(b.dataset.period!==undefined){period=+b.dataset.period;render();}
if(b.dataset.storyTab){storyTab=b.dataset.storyTab;render();}
if(b.dataset.tag!==undefined){tag=tag===b.dataset.tag?'':b.dataset.tag;render();}
if(b.dataset.reaction){const key=b.dataset.reaction,previous=state.reactions[key];state.reactions[key]=!previous;if(persist())$('#story-list').innerHTML=storyCards();else state.reactions[key]=previous;}
if(b.dataset.practice)openPractice(b.dataset.practice);
if(b.classList.contains('close')||b.id==='end-practice')stopPractice();
if(b.dataset.feedback){state.feedback.push({text:b.dataset.feedback,time:Date.now()});if(persist())toast(b.dataset.feedback.includes('更糟')?'先停下练习，找信任的人聊聊，不必独自承受。':'已记下此刻的感受，谢谢你照顾自己。');else state.feedback.pop();}
if(b.id==='save-worries'){const note=$('#worries').value.trim();if(!note){toast('先写下一点想法吧。');return;}state.entries.unshift({id:crypto.randomUUID(),mood:'焦虑',intensity:3,triggers:[],note,time:Date.now()});if(persist()){stopPractice();location.hash='today';toast('已保存到情绪日记');}else state.entries.shift();}
if(b.id==='play-sound'){if(audioContext){await audioContext.close();audioContext=null;b.textContent='播放音景';}else{try{audioContext=new(window.AudioContext||window.webkitAudioContext)();await audioContext.resume();[174.61,261.63,349.23].forEach((f,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.value=f;g.gain.value=.025/(i+1);o.connect(g).connect(audioContext.destination);o.start();});b.textContent='暂停音景';}catch{toast('当前浏览器无法播放音景');if(audioContext)audioContext.close().catch(()=>{});audioContext=null;}}}
if(b.id==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='心晴日记-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
if(b.id==='clear'&&confirm('确定清除这台设备上的全部心晴记录？此操作无法撤销，请先导出备份。')){const previous=state;state={entries:[],stories:[],reactions:{},feedback:[]};if(persist()){render();toast('本地数据已清除');}else state=previous;}
});
document.addEventListener('input',e=>{if(e.target.id==='intensity')$('#intensity-value').textContent=e.target.value+'/5';if(e.target.id==='note')$('#note-count').textContent=e.target.value.length+'/500';if(e.target.id==='story-body')$('#story-count').textContent=e.target.value.length+'/500';if(e.target.id==='story-search'){search=e.target.value;$('#story-list').innerHTML=storyCards();}});
document.addEventListener('submit',e=>{
if(e.target.id==='record-form'){e.preventDefault();state.entries.unshift({id:crypto.randomUUID(),mood:selectedMood,intensity:+$('#intensity').value,triggers:[...selectedTriggers],note:$('#note').value.trim(),time:Date.now()});if(persist()){selectedTriggers.clear();location.hash='today';toast('记录好了。每一种感受，都值得被看见。');}else state.entries.shift();}
if(e.target.id==='share-form'){e.preventDefault();const title=$('#story-title').value.trim(),body=$('#story-body').value.trim();if(!title||!body){toast('请填写标题和故事内容');return;}state.stories.unshift({id:crypto.randomUUID(),name:$('#anonymous').checked?'匿名的小树':'晴',title,body,tags:[$('#story-topic').value],type:$('#through').checked?'through':'all',time:'本地故事 · '+new Date().toLocaleDateString('zh-CN')});if(persist()){storyTab='all';tag='';search='';location.hash='stories';toast('故事已保存在这台设备');}else state.stories.shift();}
});
$('#practice').addEventListener('close',stopPractice);window.addEventListener('hashchange',render);render();
